- name: Check if .oh-my-zsh exists
  stat:
    path: ~/.oh-my-zsh
  register: stat_oh_my_zsh_result

- name: Install PowerLevel10k for zsh
  git: repo=https://github.com/romkatv/powerlevel10k.git dest=~/.zsh/powerlevel10k force=yes
  when: not stat_oh_my_zsh_result.stat.exists

- name: Install PowerLevel10k for oh-my-zsh
  git: repo=https://github.com/romkatv/powerlevel10k.git dest=~/.oh-my-zsh/custom/themes/powerlevel10k force=yes
  when: stat_oh_my_zsh_result.stat.exists

- name: Add source to .zshrc
  lineinfile:
    path: "{{ lookup('env', 'HOME') }}/.zshrc"
    line: 'source ~/.zsh/powerlevel10k/powerlevel10k.zsh-theme'
  when: not stat_oh_my_zsh_result.stat.exists

- name: Set theme for oh-my-zsh .zshrc
  lineinfile:
    path: "{{ lookup('env', 'HOME') }}/.zshrc"
    regexp: '^ZSH_THEME=.*'
    line: 'ZSH_THEME="powerlevel10k/powerlevel10k"'
  when: stat_oh_my_zsh_result.stat.exists

- name: Add config to .zshrc
  lineinfile:
    path: "{{ lookup('env', 'HOME') }}/.zshrc"
    line: '[[ ! -f ~/.p10k.zsh ]] || source ~/.p10k.zsh'


- name: Copy .p10k.zsh
  copy: src=p10k.zsh dest={{ lookup('env', 'HOME') }}/.p10k.zsh
