- name: Cloning oh-my-zsh
  git: repo=https://github.com/robbyrussell/oh-my-zsh dest=~/.oh-my-zsh

- name: Creating new ~/.zshrc
  copy: src=~/.oh-my-zsh/templates/zshrc.zsh-template dest=~/.zshrc

- name: Create plugins list as a file
  lineinfile:
    path: "{{ lookup('env', 'HOME') }}/.oh-my-zsh/plugins.lst"
    create: yes
    line: 'git'

- name: Enable plugins from file
  lineinfile:
    path: "{{ lookup('env', 'HOME') }}/.zshrc"
    regexp: '^plugins=.*'
    line: 'plugins=($(<~/.oh-my-zsh/plugins.lst))'
