- name: Cloning fzf
  git: repo=https://github.com/junegunn/fzf.git dest=~/.fzf

- name: Install fzf
  shell: ~/.fzf/install

- name: Check if .oh-my-zsh exists
  stat:
    path: ~/.oh-my-zsh
  register: stat_oh_my_zsh_result

- name: Enable fzf plugin for oh-my-zsh
  lineinfile:
    path: "{{ lookup('env', 'HOME') }}/.oh-my-zsh/plugins.lst"
    line: 'fzf'
  when: stat_oh_my_zsh_result.stat.exists

- name: Set fzf opts
  lineinfile:
    path: "{{ lookup('env', 'HOME') }}/.zshrc"
    regexp: 'export FZF_DEFAULT_OPTS=.*'
    line: "export FZF_DEFAULT_OPTS='--height 40% --layout=reverse --border'"
